sonar.projectKey=FRmicrow_dataFootV1
sonar.host.url=http://localhost:9000
sonar.token=squ_be8a389062712516545f65de85cd999f30feec73

sonar.sources=frontend/src,backend/src
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/test/**,**/tsconfig.json,**/jsconfig.json,package.json,package-lock.json,backend/node_modules_host_backup/**,**/@bcoe/v8-coverage/**

sonar.tests=frontend/src,backend/src
sonar.test.inclusions=**/*.test.js,**/*.spec.js

sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info,backend/coverage/lcov.info
sonar.javascript.forceNoTsConfig=true
sonar.typescript.tsconfigPath=
