DROP TABLE IF EXISTS V3_Player_Stats;
DROP TABLE IF EXISTS V3_League_Seasons;
DROP TABLE IF EXISTS V3_Players;
DROP TABLE IF EXISTS V3_Teams;
DROP TABLE IF EXISTS V3_Venues;
DROP TABLE IF EXISTS V3_Leagues;
DROP TABLE IF EXISTS V3_Countries;
