sonar.projectKey=FRmicrow_dataFootV1
sonar.host.url=http://localhost:9000
sonar.token=squ_bd6c174593674898db3fe56369dc2b36372b0bcf

sonar.sources=frontend/src,backend/src
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/test/**,backend/node_modules_host_backup/**,**/@bcoe/v8-coverage/**

sonar.tests=frontend/src,backend/src
sonar.test.inclusions=**/*.test.js,**/*.spec.js

sonar.javascript.node.runtime=/usr/local/bin/node
sonar.javascript.forceNoTsConfig=true
