
export const CLUB_MAPPINGS = {
    // 🇫🇷 French clubs
    'PSG': 'Paris Saint Germain',
    'Paris Saint-Germain': 'Paris Saint Germain',
    'Paris Saint-GermainT': 'Paris Saint Germain',
    'Paris SG': 'Paris Saint Germain',
    'Paris FC': 'Paris FC',
    'AS Saint-Étienne': 'Saint-Etienne',
    'Saint-Étienne': 'Saint-Etienne',
    'ASSE': 'Saint-Etienne',
    'Olympique de Marseille': 'Marseille',
    'OM': 'Marseille',
    'Olympique Lyonnais': 'Lyon',
    'Lyon': 'Lyon',
    'OL': 'Lyon',
    'AS Monaco': 'Monaco',
    'FC Nantes': 'Nantes',
    'Girondins de Bordeaux': 'Bordeaux',
    'OGC Nice': 'Nice',
    'Montpellier HSC': 'Montpellier',
    'RC Strasbourg': 'Strasbourg',
    'FC Sochaux-Montbéliard': 'Sochaux',
    'Stade Rennais FC': 'Rennes',
    'Stade Rennais': 'Rennes',

    // Mapping to DB Names (which are often the short names)
    'Lille OSC': 'Lille',
    'LOSC': 'Lille',
    'RC Lens': 'Lens',
    'FC Metz': 'Metz',
    'Toulouse FC': 'Toulouse',
    'FC Lorient': 'Lorient',
    'Angers SCO': 'Angers',
    'Le Havre AC': 'Le Havre',
    'Stade Brestois 29': 'Stade Brestois 29', // DB has full name
    'Stade Brestois': 'Stade Brestois 29',

    // 🇪🇸 Spanish clubs
    'Real Madrid': 'Real Madrid',
    'Real Madrid CF': 'Real Madrid',
    'FC Barcelone': 'Barcelona',
    'FC Barcelona': 'Barcelona',
    'Barcelona': 'Barcelona',
    'Barça': 'Barcelona',
    'Atlético de Madrid': 'Atletico Madrid',
    'Atlético Madrid': 'Atletico Madrid',
    'Atletico': 'Atletico Madrid',
    'Athletic Bilbao': 'Athletic Club',
    'Athletic Club': 'Athletic Club',
    'Valence': 'Valencia',
    'Valencia CF': 'Valencia',
    'Real Sociedad': 'Real Sociedad',
    'Séville': 'Sevilla',
    'Sevilla FC': 'Sevilla',
    'Betis Séville': 'Real Betis',
    'Real Betis': 'Real Betis',
    'Villarreal CF': 'Villarreal',
    'Villarreal': 'Villarreal',

    // 🇩🇪 German clubs
    'FC Bayern Munich': 'Bayern Munich',
    'Bayern Munich': 'Bayern Munich',
    'Bayern München': 'Bayern Munich',
    'Borussia Dortmund': 'Borussia Dortmund',
    'BVB': 'Borussia Dortmund',
    'RB Leipzig': 'RB Leipzig',
    'Bayer Leverkusen': 'Bayer Leverkusen',
    'Bayer 04 Leverkusen': 'Bayer Leverkusen',
    'Borussia Mönchengladbach': 'Borussia Monchengladbach',
    'Borussia M\'gladbach': 'Borussia Monchengladbach',
    'VfB Stuttgart': 'VfB Stuttgart',
    'Werder Bremen': 'Werder Bremen',
    'Werder Brême': 'Werder Bremen',
    'Hamburger SV': 'Hamburg',
    'Hambourg': 'Hamburg',
    'FC Koln': 'FC Koln',
    '1. FC Cologne': 'FC Koln',
    '1. FC Köln': 'FC Koln',
    'Eintracht Frankfurt': 'Eintracht Frankfurt',
    'VfL Wolfsburg': 'Wolfsburg',
    'FC Schalke 04': 'Schalke 04',
    'Schalke 04': 'Schalke 04',
    'MSV Duisburg': 'MSV Duisburg',
    'Kaiserslautern': '1. FC Kaiserslautern',
    '1. FC Kaiserslautern': '1. FC Kaiserslautern',
    '1. FC Nürnberg': '1. FC Nurnberg',
    'FC Nuremberg': '1. FC Nurnberg',
    'FC Augsburg': 'FC Augsburg',
    'Augsburg': 'FC Augsburg',
    '1. FSV Mainz 05': 'FSV Mainz 05',
    'Mainz 05': 'FSV Mainz 05',
    'Mainz': 'FSV Mainz 05',
    'TSG Hoffenheim': '1899 Hoffenheim',
    'Hoffenheim': '1899 Hoffenheim',
    '1. FC Heidenheim': '1. FC Heidenheim',
    'Heidenheim': '1. FC Heidenheim',
    'FC St. Pauli': 'St. Pauli',
    'St. Pauli': 'St. Pauli',
    '1. FC Union Berlin': 'Union Berlin',
    'Union Berlin': 'Union Berlin',
    'SC Freiburg': 'SC Freiburg',
    'Freiburg': 'SC Freiburg',


    // 🏴 English clubs
    'Manchester United': 'Manchester United',
    'Man United': 'Manchester United',
    'Manchester City': 'Manchester City',
    'Man City': 'Manchester City',
    'Liverpool': 'Liverpool',
    'Liverpool FC': 'Liverpool',
    'Arsenal': 'Arsenal',
    'Arsenal FC': 'Arsenal',
    'Chelsea': 'Chelsea',
    'Chelsea FC': 'Chelsea',
    'Tottenham Hotspur': 'Tottenham',
    'Tottenham': 'Tottenham',
    'Spurs': 'Tottenham',
    'Newcastle United': 'Newcastle',
    'Newcastle': 'Newcastle',
    'Aston Villa': 'Aston Villa',
    'Everton': 'Everton',
    'Leeds United': 'Leeds',
    'Leeds': 'Leeds',
    'Nottingham Forest': 'Nottingham Forest',
    'West Ham United': 'West Ham',
    'West Ham': 'West Ham',
    'Leicester City': 'Leicester',
    'Leicester': 'Leicester',
    'Blackburn Rovers': 'Blackburn',
    'Blackburn': 'Blackburn',
    'Wolverhampton Wanderers': 'Wolverhampton Wanderers',
    'Wolves': 'Wolverhampton Wanderers',
    'Sunderland': 'Sunderland',
    'Sheffield United': 'Sheffield United',
    'Huddersfield Town': 'Huddersfield',
    'Preston North End': 'Preston',
    'Derby County': 'Derby',
    'Ipswich Town': 'Ipswich',

    // 🇮🇹 Italian clubs
    'Juventus FC': 'Juventus',
    'Juventus': 'Juventus',
    'FC Internazionale Milano': 'Inter',
    'Internazionale': 'Inter',
    'Inter Milan': 'Inter',
    'Inter': 'Inter',
    'AC Milan': 'AC Milan',
    'Milan': 'AC Milan',
    'SSC Napoli': 'Napoli',
    'Napoli': 'Napoli',
    'AS Roma': 'Roma',
    'Roma': 'Roma',
    'Lazio': 'Lazio',
    'SS Lazio': 'Lazio',
    'Atalanta BC': 'Atalanta',
    'Fiorentina': 'Fiorentina',
    'ACF Fiorentina': 'Fiorentina',
    'Torino FC': 'Torino',
    'Torino': 'Torino',
    'Genoa CFC': 'Genoa',
    'Genoa': 'Genoa',
    'Bologna FC': 'Bologna',
    'Bologna': 'Bologna',
    'UC Sampdoria': 'Sampdoria',
    'Sampdoria': 'Sampdoria',
    'Cagliari Calcio': 'Cagliari',
    'Cagliari': 'Cagliari',
    'Hellas Verona FC': 'Verona',
    'Hellas Verona': 'Verona',
    'Hellas Vérone': 'Verona',
    'Parma Calcio 1913': 'Parma',
    'Parma Calcio': 'Parma',
    'Parma': 'Parma',
    'Como 1907': 'Como',
    'Como': 'Como',
    'US Cremonese': 'Cremonese',
    'Cremonese': 'Cremonese',
    'US Lecce': 'Lecce',
    'Lecce': 'Lecce',
    'Pisa SC': 'Pisa',
    'Pisa': 'Pisa',
    'US Sassuolo': 'Sassuolo',
    'Sassuolo': 'Sassuolo',
    'Udinese Calcio': 'Udinese',
    'Udinese': 'Udinese',

    // 🟠 Other notable European clubs
    'FC Porto': 'Porto',
    'FC Basel': 'Basel',
    'SL Benfica': 'Benfica',
    'Benfica': 'Benfica',
    'Ajax Amsterdam': 'Ajax',
    'Ajax': 'Ajax',
    'Celtic FC': 'Celtic',
    'Celtic': 'Celtic',
    'Rangers FC': 'Rangers',
    'Rangers': 'Rangers',
    'Sporting CP': 'Sporting CP',
    'Sporting Portugal': 'Sporting CP',
    'SC Braga': 'SC Braga',
    'Braga': 'SC Braga',
    'Boavista FC': 'Boavista',
    'Boavista': 'Boavista',
    'Santa Clara': 'Santa Clara',
    'Gil Vicente': 'GIL Vicente',
    'Estoril Praia': 'Estoril',
    'Estoril': 'Estoril',
    'Moreirense': 'Moreirense',
    'Portimonense': 'Portimonense',
    'Marítimo': 'Maritimo',
    'Vitória SC': 'Vitoria', // Guimaraes often just Vitoria in some DBs or one of the Vitoria entries
    'Vitória Guimarães': 'Vitoria',
    'Vitória FC': 'Vitoria Setubal',
    'Paços de Ferreira': 'Pacos Ferreira',
    'Famalicão': 'Famalicao',
};
